/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista.GestionGrupo;

import Controlador.ControllerSql;
import Controlador.FuncionesController;
import Modelo.Materia;
import Modelo.Perfil;
import static Vista.SuperAdministrador.CUPUsuario.comboHabien;
import static Vista.SuperAdministrador.CUPUsuario.comboPerfil;
import static Vista.SuperAdministrador.CUPUsuario.comboTipoC;
import debug.Consola;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.ResultSet;
import java.util.List;
import javax.swing.JComboBox;
import javax.swing.JTextField;

/**
 *
 * @author negro
 */
public class CUPGrupos extends javax.swing.JFrame {

    ControllerSql obj = new ControllerSql();
    FuncionesController cc = new FuncionesController();
    private final List<Materia> Materia;
    CallableStatement cts;
    Connection cn;
    ResultSet r;
    
    
    /**
     * Creates new form CUPGrupos
     */
    public CUPGrupos() {
        setUndecorated(true);
        initComponents();
        
        obj = ControllerSql.getInstancia();
       
       /*cargar los datos del perfil en el combo*/
       comboMateria.setModel(new javax.swing.DefaultComboBoxModel(cc.listaMateria().toArray()));
       Materia = cc.listaMateria();
       comboMateria.setSelectedIndex(0);
       
       /*Desactiva los combos que son utilizados para el numero de bloques por grupo materia*/
       
       JlabelB1.setVisible(false);
       JlabelB2.setVisible(false);
       JlabelB3.setVisible(false);
       JlabelB4.setVisible(false);
       
       
       combloqDia1.setVisible(false);
       combloqDia2.setVisible(false);
       combloqDia3.setVisible(false);
       combloqDia4.setVisible(false);
       
       combloqHora1.setVisible(false);
       combloqHora2.setVisible(false);
       combloqHora3.setVisible(false);
       combloqHora4.setVisible(false);
       
       comboS1.setVisible(false);
       comboS2.setVisible(false);
       comboS3.setVisible(false);
       comboS4.setVisible(false);
       
       
       
       
       
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        JlabelB1 = new javax.swing.JLabel();
        comboMateria = new javax.swing.JComboBox();
        txtGrupo = new javax.swing.JTextField();
        comboJornada = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        comboBloques = new javax.swing.JComboBox();
        combloqDia1 = new javax.swing.JComboBox();
        combloqHora1 = new javax.swing.JComboBox();
        combloqDia2 = new javax.swing.JComboBox();
        combloqHora2 = new javax.swing.JComboBox();
        combloqDia3 = new javax.swing.JComboBox();
        combloqHora3 = new javax.swing.JComboBox();
        combloqDia4 = new javax.swing.JComboBox();
        combloqHora4 = new javax.swing.JComboBox();
        JlabelB2 = new javax.swing.JLabel();
        JlabelB3 = new javax.swing.JLabel();
        JlabelB4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        comboS1 = new javax.swing.JComboBox();
        comboS2 = new javax.swing.JComboBox();
        comboS3 = new javax.swing.JComboBox();
        comboS4 = new javax.swing.JComboBox();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Materia");

        jLabel2.setText("Grupo");

        jLabel3.setText("Jornada");

        jLabel4.setText("Numero Bloques");

        JlabelB1.setText("Bloque 1");

        comboJornada.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Diurna", "Nocturna" }));

        jButton1.setText("Guardar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/minimizar.png"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/cerrar2.png"))); // NOI18N
        jButton6.setText("jButton2");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        comboBloques.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccionar", "1", "2", "3", "4" }));
        comboBloques.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboBloquesItemStateChanged(evt);
            }
        });

        combloqDia1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccionar", "Lunes", "Martes", "Miercoles", "Jueves", "Viernes", "Sabado" }));

        combloqHora1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccionar", "6:00 - 7:00 ", "7:00 - 8:00 ", "8:00 - 9:00 ", "9:00 - 10:00 ", "10:00 - 11:00 ", "11:00 - 12:00 ", "12:00 - 13:00 ", "13:00 - 14:00 ", "14:00 - 15:00 ", "15:00 - 16:00 ", "16:00 - 17:00 ", "17:00 - 18:00 ", "18:00 - 19:00 ", "19:00 - 20:00 ", "20:00 - 21:00 ", "21:00 - 22:00 " }));

        combloqDia2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccionar", "Lunes", "Martes", "Miercoles", "Jueves", "Viernes", "Sabado" }));

        combloqHora2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccionar", "6:00 - 7:00 ", "7:00 - 8:00 ", "8:00 - 9:00 ", "9:00 - 10:00 ", "10:00 - 11:00 ", "11:00 - 12:00 ", "12:00 - 13:00 ", "13:00 - 14:00 ", "14:00 - 15:00 ", "15:00 - 16:00 ", "16:00 - 17:00 ", "17:00 - 18:00 ", "18:00 - 19:00 ", "19:00 - 20:00 ", "20:00 - 21:00 ", "21:00 - 22:00 " }));

        combloqDia3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccionar", "Lunes", "Martes", "Miercoles", "Jueves", "Viernes", "Sabado" }));

        combloqHora3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccionar", "6:00 - 7:00 ", "7:00 - 8:00 ", "8:00 - 9:00 ", "9:00 - 10:00 ", "10:00 - 11:00 ", "11:00 - 12:00 ", "12:00 - 13:00 ", "13:00 - 14:00 ", "14:00 - 15:00 ", "15:00 - 16:00 ", "16:00 - 17:00 ", "17:00 - 18:00 ", "18:00 - 19:00 ", "19:00 - 20:00 ", "20:00 - 21:00 ", "21:00 - 22:00 " }));

        combloqDia4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccionar", "Lunes", "Martes", "Miercoles", "Jueves", "Viernes", "Sabado" }));

        combloqHora4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccionar", "6:00 - 7:00 ", "7:00 - 8:00 ", "8:00 - 9:00 ", "9:00 - 10:00 ", "10:00 - 11:00 ", "11:00 - 12:00 ", "12:00 - 13:00 ", "13:00 - 14:00 ", "14:00 - 15:00 ", "15:00 - 16:00 ", "16:00 - 17:00 ", "17:00 - 18:00 ", "18:00 - 19:00 ", "19:00 - 20:00 ", "20:00 - 21:00 ", "21:00 - 22:00 " }));

        JlabelB2.setText("Bloque 2");

        JlabelB3.setText("Bloque 3");

        JlabelB4.setText("Bloque 4");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Crear Grupo");

        jLabel6.setText("Dia");

        jLabel7.setText("Hora");

        jLabel8.setText("Salon");

        comboS1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccionar", "Salon 1", "Salon 2" }));

        comboS2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccionar", "Salon 1", "Salon 2" }));

        comboS3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccionar", "Salon 1", "Salon 2" }));

        comboS4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccionar", "Salon 1", "Salon 2" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JlabelB4)
                                    .addComponent(JlabelB3)
                                    .addComponent(JlabelB2)
                                    .addComponent(JlabelB1))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(comboBloques, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(comboJornada, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(comboMateria, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(txtGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGap(130, 130, 130))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(45, 45, 45)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(combloqDia4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(combloqDia3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(combloqDia2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(combloqDia1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(26, 26, 26)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7)
                                            .addComponent(combloqHora1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(combloqHora2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(combloqHora3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(combloqHora4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel8)
                                            .addComponent(comboS1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(comboS2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(comboS3, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(comboS4, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(27, 27, 27))
                            .addComponent(jButton1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(111, 111, 111)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(244, 244, 244)
                        .addComponent(JlabelB1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JlabelB2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JlabelB3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JlabelB4))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(comboMateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(comboJornada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(comboBloques, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(combloqDia1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(combloqHora1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboS1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(combloqDia2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(combloqHora2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboS2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(combloqDia3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(combloqHora3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboS3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(combloqDia4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(combloqHora4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboS4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        setExtendedState(ICONIFIED);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

   /*
    Genera el numero de bloques para 
    */ 
    
    private void comboBloquesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboBloquesItemStateChanged
        // TODO add your handling code here:
        
        GenerarNoBloques(0);
    }//GEN-LAST:event_comboBloquesItemStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       guardarBloque();
    }//GEN-LAST:event_jButton1ActionPerformed

    
    /*
@funcion que realiza en cambio de combos para que muestre las demas los demas bloques maximo 4
cuando se va a registar un grupo
@autor jose vanegas - jvanegasv@ucentral.edu.co
*/
public void GenerarNoBloques(int a)
    {
    // TODO add your handling code here:
            Object nBloques= comboBloques.getSelectedItem();
            
            String ab = (String) nBloques;
            int y = Integer.parseInt(ab);
            log(String.valueOf(y));
            

            if(y == 1)
                {
                    
                    
                    JlabelB1.setVisible(true);
                    combloqDia1.setVisible(true);
                    combloqHora1.setVisible(true);
                    comboS1.setVisible(true);
                   
                    
                }
            else{
            
                if(y ==2)
                {
                    
                    JlabelB1.setVisible(true);
                    JlabelB2.setVisible(true);
                    combloqDia1.setVisible(true);
                    combloqHora1.setVisible(true);
                    combloqDia2.setVisible(true);
                    combloqHora2.setVisible(true);
                    comboS1.setVisible(true);
                    comboS2.setVisible(true);
                    
                    
                    
                }
                
                else{
                
                    
                if(y == 3)
                {
                    JlabelB1.setVisible(true);
                    JlabelB2.setVisible(true);
                    JlabelB3.setVisible(true);
                    combloqDia1.setVisible(true);
                    combloqHora1.setVisible(true);
                    combloqDia2.setVisible(true);
                    combloqHora2.setVisible(true);
                    combloqDia3.setVisible(true);
                    combloqHora3.setVisible(true);
                    comboS1.setVisible(true);
                    comboS2.setVisible(true);
                    comboS3.setVisible(true);
                    
                }
                else
                    
                {
                if(y == 4)
                {
                    
                     JlabelB1.setVisible(true);
                    JlabelB2.setVisible(true);
                    JlabelB3.setVisible(true);
                    JlabelB4.setVisible(true);
                    combloqDia1.setVisible(true);
                    combloqHora1.setVisible(true);
                    combloqDia2.setVisible(true);
                    combloqHora2.setVisible(true);
                    combloqDia3.setVisible(true);
                    combloqHora3.setVisible(true);
                    combloqDia4.setVisible(true);
                    combloqHora4.setVisible(true);
                    comboS1.setVisible(true);
                    comboS2.setVisible(true);
                    comboS3.setVisible(true);
                    comboS4.setVisible(true);
                    
                    
                    
                }
                
                }
                    
                    
                
                }
        }
        

    
}

    /*Funciones*/
/*
@funcion guardar bloque 
@autor jose vanegas - jvanegasv@ucentral.edu.co
*/    
public void guardarBloque()
{


}

    
    /*
    @Valida Campos vacios
    @auto jvanegasv@ucentral.edu.co
    */
    
      public boolean ValidarCamposVacios(JTextField... textFields) {
        for (JTextField textField : textFields) {
            if (textField.getText().isEmpty()) {
                return true;
            }
        }
        return false;
    }
 
     /*
    @Valida que los campor solo contengan numeros
    @auto jvanegasv@ucentral.edu.co
    */    
      
    public void ValidadSoloNumeros(JTextField a) {
        a.addKeyListener(new KeyAdapter() {
            public void keyTyped(KeyEvent e) {
                Character ch = e.getKeyChar();
                if (!Character.isDigit(e.getKeyChar()) && (ch != KeyEvent.VK_BACK_SPACE) && (ch != '.')) {
         // if(((ch < '0') || (ch > '9')) && (ch != KeyEvent.VK_BACK_SPACE)&& (ch !='.')){ 

                    getToolkit().beep();
                    e.consume();;
                }
            }
        });
    }

    /*
    @Valida que los campor solo contengan caracteres
    @auto jvanegasv@ucentral.edu.co
    */    
    
    public void ValidadCaracteres(JTextField a) {
        a.addKeyListener(new KeyAdapter() {
            public void keyTyped(KeyEvent e) {
                Character ch = e.getKeyChar();
                if (Character.isDigit(e.getKeyChar())) {
         // if(((ch < '0') || (ch > '9')) && (ch != KeyEvent.VK_BACK_SPACE)&& (ch !='.')){ 

                    getToolkit().beep();
                    e.consume();;
                }

            }
        });
    }


   public void log(String a) {
        System.out.println("la valor  = " + " " + a);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CUPGrupos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CUPGrupos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CUPGrupos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CUPGrupos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CUPGrupos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JlabelB1;
    private javax.swing.JLabel JlabelB2;
    private javax.swing.JLabel JlabelB3;
    private javax.swing.JLabel JlabelB4;
    private javax.swing.JComboBox combloqDia1;
    private javax.swing.JComboBox combloqDia2;
    private javax.swing.JComboBox combloqDia3;
    private javax.swing.JComboBox combloqDia4;
    private javax.swing.JComboBox combloqHora1;
    private javax.swing.JComboBox combloqHora2;
    private javax.swing.JComboBox combloqHora3;
    private javax.swing.JComboBox combloqHora4;
    private javax.swing.JComboBox comboBloques;
    private javax.swing.JComboBox comboJornada;
    public static javax.swing.JComboBox comboMateria;
    private javax.swing.JComboBox comboS1;
    private javax.swing.JComboBox comboS2;
    private javax.swing.JComboBox comboS3;
    private javax.swing.JComboBox comboS4;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtGrupo;
    // End of variables declaration//GEN-END:variables
}
